chore: Add CODEOWNERS file and initial action.yml configuration

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,42 +1,114 @@
-# This file specifies the code owners for the project.
-# The people listed below will be automatically requested for review when changes are made to the code they own.
-
-* @alvarogarciapizname: 'GAWG Validate Build'
-description: 'This actiosn belogns to the GAWG workflow and is used to validate the configurations, Dockerfile, secrets, deployment, and runner.'
+name: 'GAWG Build action'
+description: 'This action checks the technology used in the project (Python or Node.js), performs a build operation, and then uploads the resulting build artifacts. The artifacts are retained for a specified number of days. This action is useful for continuous integration workflows where you want to build your project and store the build output for later use or deployment.'
 author: Álvaro García Pizarro
 branding:
-  icon: 'settings'
+  icon: 'cpu'
   color: 'gray-dark'
 
 inputs:
   technology:
     type: string
-    description: 'Repository name with owner. For example, actions/checkout'
+    description: 'Technology to use for the build. Avaliable options: maven, python, node.'
+    required: true
 
-  docker:
-    type: boolean
-    description: 'Flag to validate the Dockerfile.'
-    default: false
-
-  self-hosted-runner:
-    type: boolean
-    description: 'Flag to validate the self-hosted runner.'
-    default: false
-
-  deployment:
+  config-json:
     type: string
-    description: 'Deployment type. For example, kubernetes, helm, etc.'
+    description: 'JSON string containing workflow config parameters.'
+    required: true
 
 outputs:
-  test:
-    description: "test"
-    value: ${{ steps.test.outputs.random-number }}
+  ARTIFACT_NAME:
+    description: 'Name of the artifact generated by the build.'
+    value: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
 
 runs:
   using: "composite"
-  id: test
   steps:
-    - name: Test
+    - name: Validate technology
       shell: bash
       run: |
-        echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
+        TECHNOLOGIES=("python" "node" "maven")
+        if [[ " ${TECHNOLOGIES[@]} " =~ " ${{ inputs.technology }} " ]]; then
+          echo "✅ ${{ inputs.technology }} is a valid technology."
+        else
+          echo "❌ Error: ${{ inputs.technology }} is not a valid technology."
+          echo "::error:: ❌ Error: ${{ inputs.technology }} is not a valid technology."
+          exit 1
+        fi
+
+    - name: Generate artifact name
+      shell: bash
+      id: artifact-name
+      run: |
+        echo "ARTIFACT_NAME=$(echo ${{ fromJson(inputs.config-json).PROJECT_NAME }}-${{ inputs.technology }}-$(date +'%Y%m%d%H%M%S'))" >> $GITHUB_OUTPUT
+
+    - name: Set-up JAVA environment
+      if: ${{ inputs.technology == 'maven' }}
+      uses: actions/setup-java@v4
+      with:
+        distribution: ${{ fromJson(inputs.config-json).JAVA_DISTRIBUTION }} # VALIDAR
+        java-version: ${{ fromJson(inputs.config-json).JAVA_VERSION }} # VALIDAR
+
+    - name: Build maven project
+      id: build-maven
+      if: ${{ inputs.technology == 'maven' }}
+      shell: bash
+      run: |
+        echo "Building maven project..."
+        mvn clean install
+
+    - name: Create JAVA artifact
+      if: ${{ inputs.technology == 'maven' }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
+        retention-days: ${{ fromJson(inputs.config-json).RETENTION_DAYS }}
+        overwrite: true
+        path: ${{ fromJson(inputs.config-json).JAVA_DIST_DIR }}
+
+    - name: Set-up Python environment
+      if: ${{ inputs.technology == 'python' }}
+      uses: actions/setup-python@v5
+      with:
+        python-version: ${{ fromJson(inputs.config-json).PYTHON_VERSION }} # VALIDAR
+
+    - name: Build python project
+      id: build-python
+      if: ${{ inputs.technology == 'python' }}
+      shell: bash
+      run: |
+        echo "Building python project..."
+        python3 -m pip install -r requirements.txt
+
+    - name: Create Python artifact
+      if: ${{ inputs.technology == 'python' }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
+        retention-days: ${{ fromJson(inputs.config-json).RETENTION_DAYS }}
+        overwrite: true
+        path: ${{ fromJson(inputs.config-json).PYTHON_DIST_DIR }}
+
+    - name: Set-up Node environment
+      if: ${{ inputs.technology == 'node' }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ fromJson(inputs.config-json).NODE_VERSION }} # VALIDAR
+
+    - name: Build node project
+      id: build-node
+      if: ${{ inputs.technology == 'node' }}
+      shell: bash
+      run: |
+        echo "Building node project..."
+        npm install
+        npm run build
+
+    - name: Create Node artifact
+      if: ${{ inputs.technology == 'node' }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
+        retention-days: ${{ fromJson(inputs.config-json).RETENTION_DAYS }}
+        overwrite: true
+        path: ${{ fromJson(inputs.config-json).NODE_DIST_DIR }}
